Modified gitflow to gitflow202

diff --git a/bump-version b/bump-version
--- a/bump-version
+++ b/bump-version
@@ -8,11 +8,11 @@ if [ $# -ne 1 ]; then
 	exit 1
 fi
 
-if ! sed 's/^GITFLOW_VERSION=.*$/GITFLOW_VERSION='$1'/g' git-flow-version > .git-flow-version.new; then
-	echo "Could not replace GITFLOW_VERSION variable." >&2
+if ! sed 's/^GITFLOW_202_VERSION=.*$/GITFLOW_202_VERSION='$1'/g' git-flow-version-202 > .git-flow-version-202.new; then
+	echo "Could not replace GITFLOW_202_VERSION variable." >&2
 	exit 2
 fi
 
-mv .git-flow-version.new git-flow-version
-git add git-flow-version
-git commit -m "Bumped version number to $1" git-flow-version
+mv .git-flow-version-202.new git-flow-version-202
+git add git-flow-version-202
+git commit -m "Bumped version number to $1" git-flow-version-202
